CGI-FR/IoT-Hub-Portal

- templates/azuredeploy.json
- templates/portalDeploy.json
Related to #85 
What's new?
- Add Azure RM Template
> add deployment template

- src/AzureIoTHub.Portal/Client/Pages/Users/Delete.razor
- src/AzureIoTHub.Portal/Client/Pages/Users/Invite.razor
- src/AzureIoTHub.Portal/Client/Pages/Users/Users.razor
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
- src/AzureIoTHub.Portal/Server/Controllers/CommandsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/ConfigsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/DeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Controllers/UsersController.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- remove B2C extension role in project
> remove role management in solution

- README.md
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceDetails.cs
- templates/azuredeploy.json
- templates/portalDeploy.json
> Prevent device creation if no model is selected

- README.md
What's new?
- README modifications
> Change documentation page url

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
> AppEUI field set as ReadOnly on DeviceDetailPage

- README.md
- src/AzureIoTHub.Portal.sln
- templates/azuredeploy.json
- templates/portalDeploy.json
What's new?
- Change documentation on readme
- Change azure templates parameters and resources
> Change azure deploy template for OIDC changes #111

- src/AzureIoTHub.Portal/Server/Managers/DeviceModelImageManager.cs
> fix #128 delete a model who got no image

- .github/workflows/publish.yml
What's new?
- Add Deploy to staging job
> Add Deploy to staging job

- templates/azuredeploy.json
What's new?
- Change Azure deploy template
> Remove Api Client Secret parameter from Azure Deploy Template

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/wwwroot/scss/app.scss
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceDetails.cs
> Validation errors are correctly displayed when required fields are missing

- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelCommandMapper.cs
> fix #145 fix cannot delete model

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
> Issue #146 image saved even if the action is aborted

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
> fix #149 add model command bugs

- user-guide.md
> Add  Working with the documentation info

- dev-guide.md
> Rename user guide to dev guide

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/wwwroot/scss/app.scss
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceDetails.cs
> Display form error messages on CreateDevice & DeviceDetail pages

- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Shared/AzureIoTHub.Portal.Shared.csproj
- src/AzureIoTHub.Portal/Shared/Models/DeviceModel.cs
> Display form error messages on CreateDeviceModel & DeviceModelDetail pages

- src/AzureIoTHub.Portal.sln
- templates/portalDeploy.json
What's new?
- Change portal deploy template to get facade auth code to Connection String
> Change portaldeploy template

- src/AzureIoTHub.Portal/Server/Managers/DeviceModelImageManager.cs
> Fix a visual issue when a model has no image

- src/AzureIoTHub.Portal/Server/Controllers/DeviceModelsController.cs
> fix #165 code scanning error

- src/AzureIoTHub.Portal/Client/Pages/Gateways/ConnectionString.razor
- src/AzureIoTHub.Portal/Client/Pages/Gateways/Detail.razor
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Managers/ConnectionStringManager.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Managers/IConnectionStringManager.cs
- src/AzureIoTHub.Portal/Server/Managers/IDeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Issue #169 automatically create enrollment group

- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
What's new?
- the condition for creating a LoRaEnrollmentGroupe was updated.
> condition on createEnrollmentGroup fix

- src/AzureIoTHub.Portal/Server/Controllers/ConfigsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Helpers/DeviceHelper.cs
Reverts CGI-FR/IoT-Hub-Portal#201
> Revert "WIP: Remove Code QL errors"

- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelCommandMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Gateways/CreateGatewayDialog.razor
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Extensions/StringExtension.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelCommandMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
> fix #179 error while deleting a gateway

- src/AzureIoTHub.Portal/Client/Pages/Gateways/CreateGatewayDialog.razor
- src/AzureIoTHub.Portal/Client/Pages/Gateways/GatewayDetailPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Shared/Models/Gateway.cs
> Update gateway detail page layout

- src/AzureIoTHub.Portal/Client/Pages/Gateways/GatewayDetailPage.razor
What's new?
- Fix CodeQL Alert
> Fix #209 -  Generic catch clause

- src/AzureIoTHub.Portal/Client/Pages/Gateways/ConnectionString.razor
- src/AzureIoTHub.Portal/Client/Pages/Gateways/GatewayDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Gateways/Logs.razor
> Small fixes on gateway detail page

- src/AzureIoTHub.Portal.Server.Tests/Controllers/GatewaysControllerTests.cs
What's new?
- Add gateway update unitary tests
> Add gateway update unitary tests

- src/AzureIoTHub.Portal.Server.Tests/Mappers/ConcentratorTwinMapperTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Server/Mappers/ConcentratorTwinMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/Concentrator/Concentrator.cs
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceListItem.cs
What's new?
- Add device friendly name to devices pages
> Add device friendly name

- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelCommandsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
What's new?
- Add Open API documentations
> Change operation names in API documentation

- src/.editorconfig
- src/AzureIoTHub.Portal.sln
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Shared/AzureIoTHub.Portal.Shared.csproj
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceModel.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceModelCommand.cs
What's new?
- Add documentation of API models
> Update Solution to provider descriptions on models

- src/AzureIoTHub.Portal.Server.Tests/Controllers/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
What's new?
- Add unit tests on LoRaWAN devices controllers
> Add unit tests on LoRaWan Devices controller

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
> fix #286 fix error when creating a device model

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
What's new?
- Change unit test instruction order
> Fix #343 - Change unit test arrange order

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal.sln
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigServices.cs
What's new?
- Use model id tag to target device configuration
> Use device id instead of device type to run device configuration

- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
> Fix #358 - Add Support LoRa Feature tag on LoRa devices

- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Better treat erros when executing LoRaWAN commands
- Update API version to Key management facade V2.0
> Fix #362 - Update API version + Better treat errors

- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Startup.cs
> Activate Metrics Endpoint

- README.md
What's new?
-  Github README change
> Update README link to B2C configuration page

- .github/workflows/publish.yml
- src/AzureIoTHub.Portal/Client/Shared/MainLayout.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/SettingsController.cs
- src/AzureIoTHub.Portal/Server/Dockerfile
What's new?
- Add portal version to page footer
> #372 - Add portal version to page footer

- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/Device/DeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/Device/DeviceListItem.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/Device/DeviceTag.cs
What's new?
- #430 
- Fixed some code scanning errors
> CustomTags device property renamed to Tags

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
> fix mismatch tag name between configuration and IoT Edge

- src/AzureIoTHub.Portal/Server/Dockerfile
- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #368 - Add Healt check endpoint

- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceProvisioningServiceManagerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
> Add ScopeID

- src/AzureIoTHub.Portal/Server/Helpers/DeviceHelper.cs
> Fix #489 - Error when getting logs from modules

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/DeviceModelValidatorTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/DevicePropertyValidatorTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/LoRaDeviceDetailsValidatorTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/LoRaDeviceModelValidatorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Validators/DeviceModelValidator.cs
- src/AzureIoTHub.Portal/Client/Validators/DevicePropertyValidator.cs
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceModelValidator.cs
> Visual changes on Device Model pages

- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
What's new?
- Fix #491 
- Fix #423
> Visual changes on IoT Edge pages

- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/ConcentratorValidatorTest.cs
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Client/Validators/ConcentratorValidator.cs
> Visual changes on concentrator pages

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
What's new?
- #486 
- Fixed minor display issues
> Commands' collapsible panel initially expanded

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
> UX: Several toggle buttons changed to radio buttons or checkboxes

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
What's new?
-Change visualization of device status
- [x ] Feature
> Change visualization of device status

- src/AzureIoTHub.Portal/Client/Pages/Configurations/ConfigDetail.razor
- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
> WIP: Add a legend tooltip on icons

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
> Added description after the model name when creating a new device

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceDetailsValidator.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
What's new?
- Fix #481 
- Remove ``useOTAA`` tag from device twin
> Fix #481 - Creating LoRa device page issues

- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/IoTHubHealthCheckTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/TableStorageHealthCheckTest.cs
> Fix #525 - Remove useless assignments to local variables

- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Add loading to concentrator list page

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> Add loading to device model

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
What's new?
- Added IsLoading boolean variable on DeviceList page to prevent unexpected behaviour from MudTable ServerData loading state. See comments on #509 for more information.
> Added IsLoading boolean on DeviceList page

- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/LoRaDeviceDetailsValidatorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/CreateLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceDetailsValidator.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceDetails.cs
> Fix mispelled ABP in several locations

- .github/workflows/arm-ttk.yml
- templates/azuredeploy.json
- templates/portalDeploy.json
What's new?
- Resolves #571 
- Fix #569 
- Apply corrections to arm templates based on arm-ttk analysis
> Automate arm templates validation wit arm ttk

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> Fix search on edge devices by type

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
> Update switches labels and add text to describe switches states

- dev-guide.md
What's new?
- Add doc about #320
> Update doc: Usage of ASPNETCORE_ENVIRONMENT to target an env #320

- src/AzureIoTHub.Portal/Server/appsettings.Production.json
Add Production env with logging config + 
Set default logging on Development env to debug
What's new?
- Implement #320
> Update logging levels by Production/Development environments #320

- concepts.md
> Add missing tags doc on devices, iot edge devices and concentrators #495

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceConfigurationsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Extensions/StringExtensionTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/CreateDeviceConfigurationsPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Shared/NavMenuTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/CreateDeviceConfigurationsPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeleteDeviceConfiguration.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceConfigurationsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Extensions/StringExtension.cs
- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigService.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/ConfigurationMetrics.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceConfig.cs
What's new?
- Fix #388 
- Resolves #373
> Feature #373 - Introduce Device settings support for non-LoRa Devices

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> fix#618 bug on concentrator

- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
What's new?
-Fix code - Concatenation in loop
> #604_concatenation_in_loop

- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/LoraDeviceMethodManagerTests.cs
- src/AzureIoTHub.Portal/Server/Managers/LoraDeviceMethodManager.cs
> Fix url path when sending commands to a sensor #600

- src/AzureIoTHub.Portal.Server.Tests.Unit/Helpers/ConfigHelperTest.cs
- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
> Issue#606 code scanning alert

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
> Issue#617 remove deduplication section 

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Edge_Devices/ModuleLogsDialogTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/EdgeDeviceClientServiceTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/ModuleLogsDialog.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/EdgeDeviceClientService.cs
- src/AzureIoTHub.Portal/Client/Services/EdgeDeviceService.cs
- src/AzureIoTHub.Portal/Client/Services/IEdgeDeviceClientService.cs
- src/AzureIoTHub.Portal/Client/_Imports.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceService.cs
- src/AzureIoTHub.Portal/Shared/Constants/CloudToDeviceMethods.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeDeviceLog.cs
> Increase retrieved edge device logs #591

- .github/workflows/arm-ttk.yml
> Enable scheduling on arm ttk ci job every day at 1:30 AM #635

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/EdgeDeviceClientServiceTests.cs
What's new?
- Fix #643 
- Fix #644 
- Fix #645 
- Fix #646
> Fix missing Dispose call on local IDisposable  #643 #644 #645 #646

- src/AzureIoTHub.Portal.Server.Tests.Unit/UnitTestsAssemblyInfo.cs
> Fix #651 - Set en-US culture to unit test assembly

- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Task/422 Change visualization of device status

- src/AzureIoTHub.Portal.Server.Tests.Unit/Exceptions/InternalServerErrorExceptionTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Extensions/ApplicationBuilderExtensionTests.cs
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Constants/ErrorTitles.cs
- src/AzureIoTHub.Portal/Server/Exceptions/BaseException.cs
- src/AzureIoTHub.Portal/Server/Exceptions/InternalServerErrorException.cs
- src/AzureIoTHub.Portal/Server/Extensions/ApplicationBuilderExtension.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Add problem details middleware configuration

- .github/workflows/arm-ttk.yml
> Add a ci setup to append the label "arm-templates" on PR #636

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
> fix Issue#601 bug on DeviceList

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
What's new?
- change deviceController parameter
- related to #601
> Change api call

- src/AzureIoTHub.Portal/Client/Validators/ConcentratorValidator.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/Concentrator.cs
> Make Concentrator's certificate Thumbprint optional

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceConfigurationsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/LoRaWan/Concentrator/ConcentratorDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Configurations/ConfigDetailTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelDetailsPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Edge_Devices/EdgeDeviceDetailPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Configurations/ConfigDetail.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeDevice.cs
> Add  a go back button to detail screens

- src/AzureIoTHub.Portal.Server.Tests.Unit/Helpers/DeviceHelperTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Helpers/DeviceHelper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceProperty.cs
What's new?
- Implement #678 
- Fix #631
> Handle properties with dot notation #678

- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
> Fix #686 Add ternary operation

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
> Fix port field width #704

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
> Disable confirmed checkbox when the command is builtin #706

- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
What's new?
- Some code refactoring
> Remove some IDE warnings

- src/AzureIoTHub.Portal.Server.Tests.Unit/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/RouterConfigManagerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ProductionConfigHandlerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Managers/RouterConfigManager.cs
- src/AzureIoTHub.Portal/Server/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Properties/launchSettings.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/CN_470_510_RP1.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/CN_470_510_RP2.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/EU_863_870.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_1.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_2.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_3.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_4.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_5.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_6.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_7.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/US_902_928_FSB_8.json
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Fix #668 
- Resolve #661
> Fix/668 spike technical analysis for sx1301 conf configuration in us + cn

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeConfigurationsController.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
> rework exceptions on edge configuration

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelCommandsControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANCommandsController.cs
> Rework exceptions on LoRaWANCommandsController #725

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceTagServiceTests.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceTagService.cs
> Rework exceptions on device tag settings #724

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceModelImageManagerTest.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceModelImageManager.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> rework exception on deviceModelsController.GetItems #711

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelsControllerTest.cs
> Issue#741 rework exception on LoRaWANDeviceModelsController

- dev-guide.md
Add dev doc on how to handle problem details exception on frontend #747
What's new?
- Implement #747
> Add dev doc on how to handle problem details exception on frontend #747

- src/AzureIoTHub.Portal/Client/Program.cs
> Fix #756 - Move to code auth flow

- .github/workflows/arm-ttk.yml
> Fix branch names on arm ttk workflow #775

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
> Add scrollable mudtabs content on missing screens #615

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Configurations/ConfigDetailTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Configurations/ConfigsTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Configurations/ConfigDetail.razor
- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
What's new?
- Implement #797 
- Implement #798
> Rework pb details on listing #797 + Rework loading behaviour #798

- dev-guide.md
What's new?
- Update dev guide page
> Update dev guide

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/HealthCheckResponseWriterTests.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/HealthCheckResponseWriter.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Add health check status details for entries in checks

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
What's new?
- Fix DeviceListPageRendersCorrectly unit test #828
> Fix DeviceListPageRendersCorrectly unit test #827

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
> Fix unit tests in CI

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Configurations/ConfigsTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Edge_Devices/EdgeDeviceDetailPageTests.cs
What's new?
- Fix units test #827
> Fix unit tests in CI #827

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Shared/AppbarTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Shared/MainLayoutTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Shared/NavMenuTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/LayoutServiceTests.cs
- src/AzureIoTHub.Portal/Client/Constants/LocalStorageKey.cs
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/ILayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/LayoutService.cs
- src/AzureIoTHub.Portal/Client/Shared/Appbar.razor
- src/AzureIoTHub.Portal/Client/Shared/MainLayout.razor
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
Enable dark mode #751 and move NavMenu logic to LayoutService #830
What's new?
- Implement #751 
- Implement #830 
- Fix some unit tests #827
> Enable dark mode #751 and move NavMenu logic to LayoutService #830

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelDetailsPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Settings/DeviceTagsPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
> Handle ProblemDetailsExceptions on frontend : Device Tags

- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Fix since #841 - See details button doesn't have any action

- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Make cursor to pointer on list items

- dev-guide.md
> Add doc on the new configs on the refresh intervals of the metrics #847

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DashboardControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Dashboard/DashboardMetricCounterTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Dashboard/DashboardMetricsTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Dashboard/DashboardTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/IndexTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DashboardLayoutServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DashboardMetricsClientServiceTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Dashboard/Dashboard.razor
- src/AzureIoTHub.Portal/Client/Pages/Dashboard/DashboardMetricCounter.razor
- src/AzureIoTHub.Portal/Client/Pages/Dashboard/DashboardMetrics.razor
- src/AzureIoTHub.Portal/Client/Pages/Index.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/DashboardLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/DashboardMetricsClientService.cs
- src/AzureIoTHub.Portal/Client/Services/IDashboardLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/IDashboardMetricsClientService.cs
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
- src/AzureIoTHub.Portal/Client/_Imports.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DashboardController.cs
> Add dashboard with metrics add main page

- src/AzureIoTHub.Portal/Client/wwwroot/css/app.css
> Fix scrollable-tab-content height

- src/AzureIoTHub.Portal/Client/Program.cs
> Set snackbar to bottom left + allow duplicated snackbars #745

- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DashboardController.cs
> Set DashboardController.GetPortalMetrics endpoint name #863

- README.md
- templates/azuredeploy.json
- templates/azuredeployUI.json
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
What's new?
- Implement #826 
To Test this feature, we could use this link : [https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FCGI-FR%2FIoT-Hub-Portal%2Fmain%2Ftemplates%2Fazuredeploy.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FCGI-FR%2FIoT-Hub-Portal%2Ffeature%2F826_deploy_without_lora%2Ftemplates%2FazuredeployUI.json](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FCGI-FR%2FIoT-Hub-Portal%2Fmain%2Ftemplates%2Fazuredeploy.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FCGI-FR%2FIoT-Hub-Portal%2Ffeature%2F826_deploy_without_lora%2Ftemplates%2FazuredeployUI.json)
> Deploy portal with and without lorawan

- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> #893 Research in the device list

- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/wwwroot/css/app.css
> Update loading bar height and color #918

- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/LoRaDeviceModelValidatorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/CreateLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceModelValidator.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceBase.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceModelBase.cs
> AppEUI moved from DeviceModel to DeviceDetails

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceModelsClientServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/LoRaWanDeviceModelsClientServiceTests.cs
- src/AzureIoTHub.Portal/Client/Services/DeviceModelsClientService.cs
- src/AzureIoTHub.Portal/Client/Services/LoRaWanDeviceModelsClientService.cs
> Fix #958 - Failed to update Avatar on device models

- src/AzureIoTHub.Portal.Server.Tests.Unit/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ProductionConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/StorageAccountHealthCheckTest.cs
- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal/Server/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/StorageAccountHealthCheck.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/TableStorageHealthCheck.cs
> Remove unused settings in the portal

- src/.editorconfig
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/LoraDeviceMethodManagerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/EdgeDevices/EdgeDeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConcentratorMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceConfigurationsClientServiceTests.cs
What's new?
- Move IDE0055 to error during build
- Fix code formatting in source
> Make IDE0055 as Error + fix formatting

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/LoRaWan/Concentrator/ConcentratorListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
> Add missing pagination on concentrators #899

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
> Remove unused variables on LoRaWANConcentratorsControllerTest #977

- README.md
- dev-guide.md
What's new?
- Resolve #992 
- Resolve #993
> Add ideas feature configuration and update Azure Deploy button on documentation

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/LoRaWAN/CreateLoRaDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/ConcentratorValidatorTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Validators/LoRaDeviceModelCommandValidatorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceModelCommandValidator.cs
- src/AzureIoTHub.Portal/Client/Validators/LoRaModelCommandValidator.cs
What's new?
- Closes #995
- Add validation on device model commands
> Fix issue when adding a new command in LoRaDeviceModel edition/creation pages

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Settings/DeviceTagsPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceTagSettingsClientServiceTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
- src/AzureIoTHub.Portal/Client/Services/DeviceTagSettingsClientService.cs
- src/AzureIoTHub.Portal/Client/Services/IDeviceTagSettingsClientService.cs
> Modification device tag setting

- src/AzureIoTHub.Portal.Server.Tests.Unit/AzureIoTHub.Portal.Server.Tests.Unit.csproj
- src/AzureIoTHub.Portal.Server.Tests.Unit/Constants/ThemeTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Shared/MainLayoutTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConcentratorMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/EdgeDeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal/Client/Constants/Theme.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Shared/MainLayout.razor
- src/AzureIoTHub.Portal/Client/_Imports.razor
> Show device id on devices list page #998

- src/AzureIoTHub.Portal/Server/Startup.cs
> Disable swagger "Try It Out" feature #1011

- .github/workflows/build.yml
> Feature/Remove swagger to markdown on CI #1013

- mkdocs.yml
> Fix edit button uri in documentation #1020

- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_1.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_2.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_3.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_4.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_5.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_6.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_7.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AU_915_928_FSB_8.json
> Add support for AU_915_928 FSBs for LoRaWAN concentrators

- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AS_923_925_1.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AS_923_925_2.json
- src/AzureIoTHub.Portal/Server/RouterConfigFiles/AS_923_925_3.json
> Fix #812 Add support for AS923

- .github/workflows/lint-documentation.yml
What's new?
- Update lint documentation ci job name
> Update lint doc ci job name

- .github/workflows/publish-documentation-new-version.yml
> Add ci job to deploy docs with new version on release #1067

- .github/workflows/publish-documentation-preview-version.yml
- overrides/main.html
What's new?
- Rename docs version name from preview to dev
> Rename docs version name when changes occurs on docs/main

- .github/workflows/publish-documentation-new-version.yml
- README.md
What's new?
- Add deploy docs with stable version on release
- Update broken urls in README
> Add deploy docs with stable version on release and update broken urls in README

- src/AzureIoTHub.Portal/Client/assets/package-lock.json
- src/AzureIoTHub.Portal/Client/assets/package.json
> Fix CWE-1333 - Regular expression denial of service in scss-tokenizer

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/assets/package-lock.json
> Fix: Device Connection Timeout field should be responsive

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
> Fix: Device Model Commands

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/wwwroot/css/app.css
> Fix: Clip device names in card on small width screens

- .github/CODEOWNERS
> Fix #1069 update CODEOWNERS

- src/AzureIoTHub.Portal/Server/Managers/DeviceModelImageManager.cs
> Fix #1122 - Set http header to blob after the upload

- src/AzureIoTHub.Portal/Client/assets/package-lock.json
- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #1136 HTTP 500 Add LoRaWan device service to depency injection

- docs/dev-guide.md
> Update documentation about contribution on docs #1156

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/CreateDevicePageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DeviceToDuplicateSelectorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceToDuplicateSelector.razor
> Add unit tests on device create/detail pages about save and duplicate feature #1001

- src/docker-compose.yml
> Add database service as a dependency to iot hub portal service on docker-compose #1175

- templates/azuredeploy.json
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
> Fix arm deployment without ideas feature #1178

- templates/azuredeploy.json
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
What's new?
- Fix arm ttk analysis related to pgsqlAdminPassword parameter type
> Set pgsqlAdminPassword parameter as securestring on arm templates

- docs/dev-guide.md
What's new?
- Documentation about new features on v3
> Merge v3 documentation to docs/main branch

- src/AzureIoTHubPortal.Domain/Base/EntityBase.cs
> Fix #1191 - Unable to track an entity of type 'DeviceModelProperty' because its primary key property 'Id' is null.

- src/docker-compose.yml
> Fix #1193 - Persist postgreSQL database for local development

- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/DatabaseHealthCheck.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #1198 - Add database HealthCheck to /Healtz response

- src/AzureIoTHub.Portal.sln
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
> Fix #1212 - Modify deployment template

- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #1206 - Configure database and migrate as soon as possible

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911190829_Add EdgeDeviceModel.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911190829_Add EdgeDeviceModel.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelSeeder.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDeviceModel.cs
> Add migration of edge models from st table to database #1217

- .github/workflows/delete-documentation-version.yml
> Add manual pipeline to delete a version of doc #1087

- docs/dev-guide.md
> Add doc about config key Job__SyncDatabaseJobRefreshIntervalInMinutes

- src/AzureIoTHub.Portal.Tests.Unit/Server/Mappers/LoRaDeviceModelMapperTests.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceModelMapper.cs
> Fix #1289 - Add ClassType to device twin configuration for loraWAN

- .devbots/lock-issue.yml
- .devbots/lock-pull-request.yml
- .devbots/needs-review.yml
- .devbots/needs-triage.yml
What's new?
- Remove unused devbot configuration files
> Remove devbot actions

- src/docker-compose.yml
> Add pgadmin on docker-compose #1310

- src/AzureIoTHub.Portal.Infrastructure/AzureIoTHub.Portal.Infrastructure.csproj
- src/AzureIoTHub.Portal.Tests.Unit/AzureIoTHub.Portal.Tests.Unit.csproj
- src/AzureIoTHub.Portal.Tests.Unit/UnitTests/Bases/BackendUnitTest.cs
- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
> Downgrade microsoft nuget dependencies from 6.0.10 to 6.0.9 #1336

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/ConcentratorDetailPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/ConcentratorListPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/CreateConcentratorPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/DeleteConcentratorPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/LoRaWanConcentratorsClientServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANConcentratorServiceTests.cs
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/DeleteConcentratorPage.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/ILoRaWanConcentratorClientService.cs
- src/AzureIoTHub.Portal/Client/Services/LoRaWanConcentratorClientService.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Services/ILoRaWANConcentratorService.cs
- src/AzureIoTHub.Portal/Server/Services/LoRaWANConcentratorService.cs
> Concentrator CRUD is now using database

- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeRoute.cs
> Fix #1390 - Add NOT token to available routes

- .github/workflows/build.yml
> Bugfix: Add github action to generate an app token for automated PR on documentation

- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelPropertySeeder.cs
What's new?
- Fix Missed opportunity to use where
> Fix Code Scaning issue #728

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Configurations/EdgeModule/ModuleDialogTests.cs
What's new?
- Remove Useless assignment to local variable
> Remove Useless assignment to local variable in ModuleDialogTests

- src/AzureIoTHub.Portal.Client/assets/package-lock.json
- src/AzureIoTHub.Portal.Client/package-lock.json
- src/AzureIoTHub.Portal/Client/assets/package.json
What's new?
- Remove scss tokenizer from dev dependency inside our project
> Remove scss_tokenizer dev dependency from the package.json file

- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/assets/package-lock.json
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceProfile.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeListItem.cs
> Change Edge device List is not showing the device name

- src/AzureIoTHub.Portal.Server/Services/LoRaWANCommandService.cs
> Fix #1467 - Failed to save LoRa WAN device model commands

- src/AzureIoTHub.Portal.Server/Services/ExternalDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ExternalDeviceServiceTests.cs
> Fix #1462 - Unable to get device credentials

- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/docker-compose.yml
> BugFix/#1385_-_Failed to sort in Edge Device list

- src/AzureIoTHub.Portal.Server/Services/DeviceModelPropertiesService.cs
- src/AzureIoTHub.Portal.Server/Services/ExternalDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ExternalDeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANCommandServiceTests.cs
What's new?
- Remove useless assignment to local variables on LoRaWAN Command Service Tests
- Use Disposable when needed in LoRaWAN  Command Service Tests
- Use better conditional statement in DeviceModel Properties Service
- Use dedicated exception catching on External Device service
> Fix Code QL analysis issues

- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal.Client/assets/package-lock.json
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/EdgeDevicesController.cs
- src/AzureIoTHub.Portal.Server/Services/EdgeDevicesService.cs
- src/AzureIoTHub.Portal.Server/Services/IEdgeDevicesService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/EdgeDeviceListFilter.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/EdgeDeviceListPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeDeviceServiceTest.cs
> Fix/1410 - Transform edge device type filter to edge model filter in the list page

- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/CreateEdgeModelsPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModule/ModuleDialogTab1.razor
- src/AzureIoTHub.Portal.Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal.Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IoTEdgeModuleEnvironmentVariable.cs
> Fix #1498 - Add environment variable validation to our models

- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
What's new?
- Remove unauthorized code when pooling is enable
> BugFix_-_The application does not compile

- src/AzureIoTHub.Portal.Client/AzureIoTHub.Portal.Client.csproj
> Bugfix/Remove references to FileDownload.js on client csproj #1565

- docs/dev-guide.md
> Add doc about config keys required by device telemery feature #1577

- docs/dev-guide/migrations/v3-to-v4.md
> Fix images urls

- src/AzureIoTHub.Portal.Client/Pages/Devices/DeleteDevicePage.razor
- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal.Client/Services/ILoRaWanDeviceClientService.cs
- src/AzureIoTHub.Portal.Client/Services/LoRaWanDeviceClientService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DeleteDevicePageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/LoRaWanDeviceClientServiceTests.cs
> Fix missing delete lorawan device on client side #1592

- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/LayoutServiceTests.cs
What's new?
- Use any cancellation token mockup instead of null one
> Use any cancellation token mockup instead of null one

- src/AzureIoTHub.Portal.Domain/Entities/Device.cs
- src/AzureIoTHub.Portal.Domain/Entities/LorawanDevice.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221128175823_Add DeviceModel FK on Device and LoRaDevice.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221128175823_Add DeviceModel FK on Device and LoRaDevice.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
> Feature: Add device model navigation property on device and lorawan device #1382

- src/AzureIoTHub.Portal.Domain/Entities/EdgeDevice.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221128225921_Add EdgeDeviceModel FK On Edge Device.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221128225921_Add EdgeDeviceModel FK On Edge Device.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
> Add edge device model navigation property on edge device #1613

- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal.Client/Pages/Devices/ImportReportDialog.razor
- src/AzureIoTHub.Portal.Client/Services/DeviceClientService.cs
- src/AzureIoTHub.Portal.Client/Services/IDeviceClientService.cs
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/AdminController.cs
- src/AzureIoTHub.Portal.Server/Managers/ExportManager.cs
- src/AzureIoTHub.Portal.Server/Managers/IExportManager.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Server/Services/ExternalDeviceService.cs
- src/AzureIoTHub.Portal.Server/Services/IDeviceService.cs
- src/AzureIoTHub.Portal.Server/Services/LoRaWanDeviceService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/ImportResultLine.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/ImportReportDialogTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/DeviceClientServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/AdminControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Managers/ExportManagerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ExternalDeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWanDeviceServiceTests.cs
> Add an Import feature for devices list

- src/AzureIoTHub.Portal.Client/Program.cs
> Bugfix: Fix missing global http progress bar #1630

- src/AzureIoTHub.Portal.Client/AzureIoTHub.Portal.Client.csproj
What's new?
- Remove duplicated package reference to Microsoft.Extensions.Http
> Bugfix: Remove duplicated package reference to Microsoft.Extensions.Http

- .github/workflows/publish.yml
What's new?
- Fix override portal image tag on app_service.bicep
> Bugfix: Fix override portal image tag on app_service.bicep

- .github/workflows/publish.yml
What's new?
- Add missing with on publish ci pipeline
> Bugfix: Add missing with on publish ci pipeline

- src/AzureIoTHub.Portal.Tests.Unit/Server/Managers/ExportManagerTests.cs
…rErrorExceptionAsync #1628
What's new?
- Fix #1628
> Fix random failure on the unit test ImportDeviceListWrongFileFormatShouldThrowInternalServerErrorExceptionAsync

- docs/dev-guide/conception/diagrams.md
- mkdocs.yml
What's new?
- Add use case diagram
- Add class diagram
> Feature: Add diagrams to the documentation

- docs/dev-guide/conception/diagrams.md
- requirements.txt
What's new?
- Add multilayer technical architecture diagram
> Feature: Add multilayer technical architecture diagram

- src/AzureIoTHub.Portal.Application/Services/ILoRaWANConcentratorService.cs
- src/AzureIoTHub.Portal.Client/Components/Concentrators/ConcentratorSearch.razor
- src/AzureIoTHub.Portal.Client/Models/ConcentratorSearchInfo.cs
- src/AzureIoTHub.Portal.Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal.Server/Services/LoRaWANConcentratorService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/ConcentratorFilter.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Components/Concentrators/ConcentratorSearchTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/ConcentratorListPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANConcentratorServiceTests.cs
- src/AzureIoTHub.Portal.sln
> enable search on concentrator page

- src/AzureIoTHub.Portal.Server/Services/LoRaWANConcentratorService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/ConcentratorFilter.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANConcentratorServiceTests.cs
What's new?
- Rename keyword to searchText in Concentrator API query param
> Rename keyword to searchText i query params on lorawan concentrators API

- src/AzureIoTHub.Portal.Application/Services/IIdeaService.cs
- src/AzureIoTHub.Portal.Client/Pages/Ideas/SubmitIdeaDialog.razor
- src/AzureIoTHub.Portal.Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/IdeasController.cs
- src/AzureIoTHub.Portal.Server/Services/IdeaService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IdeaRequest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Ideas/SubmitIdeaDialogTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/IdeasControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/IdeaServiceTests.cs
> Enable collect and send technical details to Awesome Ideas

- templates/app_service.bicep
> Fix #1821 - ARM template validation failed

- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceListPage.razor
> Fix Device List Page

- src/AzureIoTHub.Portal.Application/Providers/IDeviceRegistryProvider.cs
- src/AzureIoTHub.Portal.Application/Services/IConfigService.cs
- src/AzureIoTHub.Portal.Infrastructure/Providers/AzureDeviceRegistryProvider.cs
- src/AzureIoTHub.Portal.Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceModelService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/CreateDevicePageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Providers/AzureDeviceRegistryProviderTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ConfigServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelServiceTests.cs
> Fix: Bug-When device model is delete some Azure resources are still there #1832

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/DeviceConfigurations/DeviceConfigurationDetailPageTests.cs
> Update unit tests device configuration detail page

- codecov.yml
> Ignore Quartz config file in codecov

- src/AzureIoTHub.Portal.Infrastructure/AzureIoTHub.Portal.Infrastructure.csproj
- src/AzureIoTHub.Portal.MySql/AzureIoTHub.Portal.MySql.csproj
- src/AzureIoTHub.Portal.Postgres/AzureIoTHub.Portal.Postgres.csproj
- src/AzureIoTHub.Portal.Server/AzureIoTHub.Portal.Server.csproj
What's new?
- Update ef core to v7.0.4
> Update ef core to 7.0.4

- .github/workflows/ci-tests.yml
What's new?
- Trying to disable E2E tests for dependabot PRs
> Update E2E tests condition

- src/AzureIoTHub.Portal.Domain/ConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerBase.cs
- src/AzureIoTHub.Portal.Infrastructure/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/ProductionConfigHandlerTests.cs
Add AWS configuration in ConfigHandler
What's new?
- #1785
> #1785 Add AWS configuration

- .github/workflows/lint-documentation.yml
- .github/workflows/publish-documentation-preview-version.yml
- .gitignore
> Feature: CI jobs should handle the branch docs/main-vnext

- src/AzureIoTHub.Portal.Infrastructure/AzureIoTHub.Portal.Infrastructure.csproj
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerFactory.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/AWSServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/AzureServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/IServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal.Server/Startup.cs
- Add CloudProvider dependencies to the Server Startup
- Add CloudProvider dependencies to the Infrastructure Startup
- Azure first in the switch to unify
What's new?
- Fix #1929
> #1929 Configuration logic by provider

- README.md
> 1943 task add a button to deploy aws infra

- src/AzureIoTHub.Portal.Server/Startup.cs
> #1937 Azure dependency fix for AWS

- src/AzureIoTHub.Portal.Infrastructure/AzureIoTHub.Portal.Infrastructure.csproj
- src/AzureIoTHub.Portal.Infrastructure/Startup/AWSServiceCollectionExtension.cs
> Add AWS Greengrass client to backend

- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelCommandSeeder.cs
> Fix #2064 - Take command name from the row key in the table

- src/AzureIoTHub.Portal.Infrastructure/ProductionAWSConfigHandler.cs
What's new?
- Fix device model max age setting handling for AWS support
> Fix Device model max age configuration handler

- .github/workflows/aws_deploy_staging.yml
> Feature: Add cd pipeline to build and deploy to aws app runner

- src/AzureIoTHub.Portal.Infrastructure/Jobs/AWS/SyncThingTypesJob.cs
What's new?
- Fix SyncThingTypesJob: Npgsql cannot handle parallel queries (multiple commands on the same connection)
> Fix SyncThingTypesJob

- templates/aws/awsdeploy.yml
What's new?
- Provision AppRunner in VPC
- Format the CFN template
> Update CNF template to provision AppRunner in VPC

- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSDevicePropertyService.cs
> Fix #2117 - Failed to load device model when adding a new property in the model

- src/AzureIoTHub.Portal.Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/CreateEdgeDevicePage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/CreateEdgeDevicePageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/EdgeDeviceDetailPageTests.cs
Remove Status in form when the CLoudProvider is AWS
What's new?
- #2126
> Remove status from form in AWS

- docs/aws.md
Add AWS AccountId attribute in the documentation
What's new?
- #2128
> Add AccountId Attribute in AWS doc

- src/AzureIoTHub.Portal.MySql/Migrations/20230531104258_Add dataprotection + edge device external identifier.Designer.cs
- src/AzureIoTHub.Portal.MySql/Migrations/20230531104258_Add dataprotection + edge device external identifier.cs
What's new?
- Create Mysql migration scripts
> Update MySQL database schema

- src/AzureIoTHub.Portal.Application/Services/IDeviceService.cs
- src/AzureIoTHub.Portal.Application/Services/IExternalDeviceService.cs
- src/AzureIoTHub.Portal.Client/Pages/Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal.Client/Services/DeviceClientService.cs
- src/AzureIoTHub.Portal.Client/Services/EdgeDeviceClientService.cs
- src/AzureIoTHub.Portal.Client/Services/IDeviceClientService.cs
- src/AzureIoTHub.Portal.Client/Services/IEdgeDeviceClientService.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AwsExternalDeviceService.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/ConnectionStringDialogTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/ConnectionStringDialogTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/DeviceClientServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/EdgeDeviceClientServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
What's new?
- Enable certificate generation for AWS and store certificate/public key/private key in storage
- Displays certificates and keys on screen
> Use certificate to authenticate devices and edge devices

- src/AzureIoTHub.Portal.Client/Pages/DeviceModels/DeviceModelListPage.razor
Change the detail buttton tooltip for device model into `see device model details`
What's new?
- #1995
> see detail device model tooltip changed

- .github/workflows/aws_deploy_staging.yml
- src/AzureIoTHub.Portal.Domain/ConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerBase.cs
- src/AzureIoTHub.Portal.Infrastructure/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/Jobs/SyncLoRaDeviceTelemetryJob.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAWSConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAzureConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/Providers/AzureDeviceRegistryProvider.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelCommandSeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelPropertySeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelSeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceTagSeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelCommandSeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelSeeder.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AwsExternalDeviceService.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/AzureServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/SettingsController.cs
- src/AzureIoTHub.Portal.Server/Filters/LoRaFeatureActiveFilterAttribute.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/ProductionAWSConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/ProductionAzureConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Providers/AzureDeviceRegistryProviderTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/SettingsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Filters/LoRaFeatureActiveFilterAttributeTest.cs
- templates/aws/awsdeploy.yml
> Prefix Azure specific parameters

- src/AzureIoTHub.Portal.Infrastructure/Services/AwsExternalDeviceService.cs
> #2156 remove edge device remove its secret

- src/AzureIoTHub.Portal.Application/Mappers/AWS/AWSDeviceThingProfile.cs
- src/AzureIoTHub.Portal.Application/Mappers/EdgeDeviceProfile.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSEdgeDevicesService.cs
- Add missing mappings
- Fix AWSEdgeDeviceService
What's new?
- Fix #2162
> #2162 Edge device loose tags

- src/IoTHub.Portal.Application/Mappers/EdgeDeviceProfile.cs
- src/IoTHub.Portal.Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/IoTHub.Portal.Infrastructure/Services/EdgeDevicesServiceBase.cs
> Display connection state on edge device

- docs/aws.md
> enable fleet index mode for AWS support

- src/IoTHub.Portal.Infrastructure/Jobs/AWS/SyncGreenGrassDeploymentsJob.cs
- src/IoTHub.Portal.Infrastructure/Jobs/AWS/SyncThingTypesJob.cs
- src/IoTHub.Portal.Infrastructure/Managers/AwsDeviceModelImageManager.cs
- src/IoTHub.Portal.Infrastructure/Services/AWS/AWSDevicePropertyService.cs
- src/IoTHub.Portal.Infrastructure/Services/AWS/AWSDeviceService.cs
- src/IoTHub.Portal.Infrastructure/Services/AWS/AWSEdgeDevicesService.cs
- src/IoTHub.Portal.Infrastructure/Services/AWS/AwsConfigService.cs
- src/IoTHub.Portal.Infrastructure/Services/AwsExternalDeviceService.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Jobs/AWS/SyncThingTypesJobTests.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Managers/AwsDeviceModelImageManagerTest.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Services/AWSDevicePropertyServiceTests.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Services/AWSDeviceServiceTests.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Services/AwsExternalDeviceServiceTests.cs
> #2169 improve aws exceptions management

- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_1.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_2.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_3.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_4.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_5.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_6.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_7.json
- src/AzureIoTHub.Portal.Infrastructure/RouterConfigFiles/AU_915_928_FSB_8.json
> Update AU915-928 sub frequency channels

- .github/workflows/ci-tests.yml
> Feature: Move codecov to dedicated ci job #2365

- src/IoTHub.Portal.Infrastructure/IoTHub.Portal.Infrastructure.csproj
- src/IoTHub.Portal.Server/IoTHub.Portal.Server.csproj
What's new?
- Uninstall Quartz dependency. Its already installed by Quartz.Extensions.DependencyInjection, Quartz.Extensions.Hosting and Quartz.Serialization.Json dependencies
> Feature: Uninstall Quartz dependency

- src/IoTHub.Portal.Server/IoTHub.Portal.Server.csproj
What's new?
- Remove nuget Microsoft.Identity.Web: It is already a dependency of Microsoft.Identity.Web.UI
> Feature: Remove nuget Microsoft.Identity.Web

- src/IoTHub.Portal.Server/Startup.cs
> Bugfix: Add missing pb details mapping on ResourceNotFoundException #2509

- templates/azure/app_service.bicep
- templates/azure/dps.bicep
> Feature: Update Microsoft.Devices/provisioningServices api version on bicep templates

- .github/workflows/ci-open-api-documentation.yml
- .github/workflows/ci-tests.yml
What's new?
- Update actions download-artifact and upload-artifact to v4
> Bump: Update actions download-artifact and upload-artifact to v4

- docs/dev-guide/migrations/v4-to-v5.md
> Add missing setting "Azure__StorageAccount__ConnectionString" to doc

- src/IoTHub.Portal.Infrastructure/RouterConfigFiles/AS_923_925_1.json
- src/IoTHub.Portal.Infrastructure/RouterConfigFiles/AS_923_925_2.json
> Fix #2766 - invert AS1 and AS2 downlink frequencies

- .github/dependabot.yml
> Execute dependabot weekly and with only one PR
