CGI-FR/IoT-Hub-Portal

- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> fix #88 rename DefaultEnrollmentGroupe to DefaultEnrollmentGroup

- README.md
- templates/azuredeploy.json
- templates/portalDeploy.json
What's new?
- Change all old links to CGI's Organization
> Migrate to CGI-FR Organization

- README.md
What's new?
- Update readme to get quickstart and deploy button available without going to documentation page
-
> Add Quick start to readme

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/Device/DeviceListItem.cs
> LastActivityTime changed to StatusUpdatedTime

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Server/Controllers/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Helpers/DeviceHelper.cs
- src/AzureIoTHub.Portal/Server/Helpers/Eui.g.cs
- src/AzureIoTHub.Portal/Server/Helpers/EuiHelper.cs
- src/AzureIoTHub.Portal/Server/Helpers/Hexadecimal.cs
- src/AzureIoTHub.Portal/Server/Helpers/Id6.cs
- src/AzureIoTHub.Portal/Server/Helpers/LetterCase.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
> fix issue #76 check the dev EUI at device creation

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
What's new?
- fix bug in device model page when loading a device that is not creating by the interface (with field missing)
> fix #102 - Check if device model is present before requesting the current device model

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Program.cs
> Fix code scanning alert - Missing Dispose call on local IDisposable

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/wwwroot/scss/app.scss
> Add space between buttons in DeviceDetailPage and DeviceModelDetailPage

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/ISSUE_TEMPLATE/user_story.md
What's new?
- Add issue templates to github
> Add issue templates

- .github/workflows/codeql.yml
> disable codeQL on pull request

- src/AzureIoTHub.Portal/Client/Pages/Gateways/Detail.razor
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Managers/ConnectionStringManager.cs
> Issue #142 connection string give an error when enrollment group doesn't exist

- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
What's new?
- Fix Deferenced variables in Config Helper
> Fix Deferenced variables revealed by CodeQL

- src/AzureIoTHub.Portal/Server/Controllers/ConfigsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
- src/AzureIoTHub.Portal/Server/Helpers/DeviceHelper.cs
What's new?
- Fix Dereferenced variable may be null
> WIP: Remove Code QL errors

- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelCommandMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Mappers/DeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal/Server/Extensions/StringExtension.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelCommandMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
What's new?
- Add unit tests for the solution
> Add Unit tests for mappers

- src/AzureIoTHub.Portal.Server.Tests/Managers/DeviceModelCommandsManagerTests.cs
What's new?
- Add unit tests on device model commands manager
> Add Device model commands manager tests

- src/AzureIoTHub.Portal.Server.Tests/AzureIoTHub.Portal.Server.Tests.csproj
- src/AzureIoTHub.Portal.Server.Tests/Controllers/GatewaysControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/GatewaysController.cs
What's new?
- Fix generic catch clause
> Fix #219 - Remove generic catch clause

- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Activate swagger endpoint with Swashbuckle
> Activate Swagger endpoint

- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelCommandsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeConfigurationsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/SettingsController.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Add API versioning
> Introduce API version 1.0

- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/DeviceModelCommandsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Managers/DeviceModelCommandsManagerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelCommandsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceModelCommandsManager.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelCommandMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceModel.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceModelCommand.cs
see: #217 
What's new?
Add the possibility (by API) to create builtin device models (and commands). These device models are not modifiable via the UI (but still with APIs). 
This provide a way to automatically deploy the solution wit builtin features that are extensible.
> Introduce bultin device models (with builtin commands)

- src/AzureIoTHub.Portal.Server.Tests/Controllers/ConcentratorsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Controllers/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceService.cs
What's new?
- Internal changes to query devices nd filter it at the IoT Hub query
- Add new unit tests to cover the IoT Hub Registry manager wrapper
> Filter devices at iot hub level

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
+ Display DeviceID when the device has no Name
+ Also allow to search on DeviceId or DeviceName in the Search Panel
What's new?
- #271
> Display DeviceID when the device has no Name

- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/EdgeConfigurationsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeConfigurationsController.cs
- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigServices.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> 288 Fix IoT Edge configuration page

- src/AzureIoTHub.Portal.Server.Tests/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
> fix #272 fix error on concentrator list

- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
> Fix #299 - Change url on configuration detail link from list page

- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #330 - Activate LoRa by default

- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Rename to ``LoRaFeature:Enabled``
> Rename LoRa Feature Setting 

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
What's new?
- Remake readonly fields if builtin
> Fix #326 - Make fields disabled if builtin

- src/AzureIoTHub.Portal/Client/Pages/Configurations/ConfigDetail.razor
- src/AzureIoTHub.Portal/Client/Pages/Configurations/Configs.razor
What's new?
- Remove unused action buttons in IoT Edge configuration pages
> Fix #300 - Remove Action buttons from IoT Edge Configuration

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
What's new?
- fix #343  - Wait unit a button is present before continuing a test
> Wait for button is present before continuing test

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
> Issue#333 bug when lora is disabled

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeConfigurationsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeConfigurationsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceModelMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/IDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigServices.cs
- src/AzureIoTHub.Portal/Server/Wrappers/ProvisioningServiceClientWrapper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceModel/LoRaDeviceModel.cs
> Device model changes should create new automatic device configuration

- src/AzureIoTHub.Portal/Client/Pages/Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
> Add DPS connection on device detail page if not lora

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelCommandsControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceTagSettingsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANCommandsController.cs
What's new?
- Remove AsPage usage sinc not needed
> Fix #308 - Remove useless pages in table queries

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/ConcentratorsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelCommandsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceTagSettingsControllerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeConfigurationsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/SettingsControllerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Filters/LoRaFeatureActiveFilterAttributeTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Helpers/HelpersTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceModelCommandsManagerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/RouterConfigManagerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/ConcentratorTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceModelCommandMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceTagMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceModelMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceTagServiceTest.cs
What's new?
- Change namespace name for unit tests
> Rename unit tests namespaces

- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/CreateConcentratorPage.razor
> Fix visual bugs on concentrator pages

- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
> Added form validation when creating a new device model

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelPropertiesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Helpers/MockHttpHelper.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelDetailsPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Validators/DevicePropertyValidator.cs
- src/AzureIoTHub.Portal/Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelPropertiesController.cs
- src/AzureIoTHub.Portal/Server/Entities/DeviceModelProperty.cs
- src/AzureIoTHub.Portal/Server/Entities/EntityBase.cs
- src/AzureIoTHub.Portal/Server/Factories/ITableClientFactory.cs
- src/AzureIoTHub.Portal/Server/Factories/TableClientFactory.cs
- src/AzureIoTHub.Portal/Server/Mappers/DevicePropertyProfile.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Shared/Models/DevicePropertyType.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceProperty.cs
> Add device model properties support

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/DeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Mappers/LoRaDeviceTwinMapperTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/IDeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceTagService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceTagService.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/Device/DeviceListItem.cs
> Make device tags searchable in the search panel on DevicesListPage

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelPropertiesControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelPropertiesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANCommandsController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelPropertiesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDeviceModelsController.cs
> Add lorawan device model custom propertis support

- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
> Menu refactoring

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceTagServiceTest.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceTagService.cs
> DeviceTagService Test

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceModelCommandsManager.cs
> Bug fix: Cannot send a LoRaWAN command with the same name on several models

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceProvisioningServiceManagerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Managers/IDeviceProvisioningServiceManager.cs
> Enrollment group creation now based on device model id

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/LoRaWAN/EditLoraDevice.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
- src/AzureIoTHub.Portal/Server/Mappers/DeviceTwinMapper.cs
> Bug Fix: Executing command to lorawan device should not change the path

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/SettingsControllerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Shared/MainLayout.razor
- src/AzureIoTHub.Portal/Client/Shared/NavMenu.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/SettingsController.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/PortalSettings.cs
> Fix #387 - Add portal name setting

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> Fix Device Model list page loading since portal settings changes

- src/AzureIoTHub.Portal.Server.Tests.Unit/Helpers/MockHttpHelper.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateDeviceModelPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceModelValidator.cs
What's new?
- Add unit test to lorawan device model creation page
> Add unit test to lorawan device model creation page

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeleteDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceDeleteConfirmationDialog.razor
> Fix #424 - display device name in screens instead of device id

- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal/Client/Shared/MainLayout.razor
- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/SettingsController.cs
> Fix #371 - Add portal name to page title

- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceProvisioningServiceManagerTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
> Feature: Add 'https://' before dps service endpoint

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Rearrange "+" buttons in list screens

- src/AzureIoTHub.Portal/Client/Pages/Devices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/ConnectionStringDialog.razor
> Fix #483 - Rename fields in connection screens

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DeviceModelsControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConfigsServicesTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigService.cs
> Fix #488  - Use model id in twin configuration names

- src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/CreateEdgeDeviceDialog.razor
> Fix 404 error when creating new IoT Edge Device

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceTagServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/IoTHubHealthCheckTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/LoRaManagementKeyFacadeHealthCheckTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/ProvisioningServiceClientHealthCheckTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/StorageAccountHealthCheckTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ServicesHealthCheck/TableStorageHealthCheckTest.cs
- src/AzureIoTHub.Portal/Server/Factories/ITableClientFactory.cs
- src/AzureIoTHub.Portal/Server/Factories/TableClientFactory.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Managers/IDeviceProvisioningServiceManager.cs
- src/AzureIoTHub.Portal/Server/Managers/ILoraDeviceMethodManager.cs
- src/AzureIoTHub.Portal/Server/Managers/LoraDeviceMethodManager.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/IoTHubHealthCheck.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/LoRaManagementKeyFacadeHealthCheck.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/ProvisioningServiceClientHealthCheck.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/StorageAccountHealthCheck.cs
- src/AzureIoTHub.Portal/Server/ServicesHealthCheck/TableStorageHealthCheck.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Server/Wrappers/IProvisioningServiceClient.cs
- src/AzureIoTHub.Portal/Server/Wrappers/ProvisioningServiceClientWrapper.cs
> Issue#369 add health probe for sub services

- templates/portalDeploy.json
Deployment of the template fails because :
- The template was referencing a non-existent variable called isLoRaFeatureEnabled: Referencing now an existing parameter with same name 
- A comma was missing
What's new?
- Fix #548
> Fix the reference to the parameter isLoRaFeatureEnabled #548

- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceConfig.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceProperty.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceTag.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceBase.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceModelBase.cs
> Fix #579 - Add default values to documentation in API models

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Configurations/ConfigsTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DeviceConfigurations/DeviceConfigurationListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DevicesListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/DeviceModelListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Edge_Devices/EdgeDeviceListPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/LoRaWan/Concentrator/ConcentratorListPageTests.cs
What's new?
- Related to #827  
- Related to #785
> Implement #827 - Fix Tests in CI

- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConcentratorMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/ConcentratorMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/EdgeDeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/EdgeDeviceMetricLoaderServiceTests.cs
> Fix missing using clause on Disposable Instances for unit tests

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Settings/DeviceTagsPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
Add refresh button on device tags #794
What's new?
- Implement #794
> Add refresh button on device tags #794

- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal/Server/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
**New options are now present on the portal**
- OIDC__ValidateIssuer
> Validation of the issuer mitigates forwarding attacks that can occur when an IdentityProvider represents multiple tenants and signs tokens with the same keys. It is possible that a token issued for the same audience could be from a different tenant. For example an application could accept users from contoso.onmicrosoft.com but not fabrikam.onmicrosoft.com, both valid tenants. An application that accepts tokens from fabrikam could forward them to the application that accepts tokens for contoso. This boolean only applies to default issuer validation. If [IssuerValidator](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.issuervalidator?view=azure-dotnet#micros …
> Merge Hotfixes from 2.3

- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
> Fix #843 - Issue when creating a new device if the DeviceID already exists

- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal/Client/Program.cs
> Add global loading bar when http events are fired

- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
> Fix loading of LoraWAN device commands #904

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Validators/DeviceDetailsValidator.cs
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceDetailsValidator.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/DeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceDetails.cs
What's new?
- #842 Modification validator
> Fix validation issue on DeviceID when creating a new LoRa Device

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/CreateLoRaDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/LoRaWAN/CreateLoRaDeviceModelPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/DevicesModels/LoRaWAN/EditLoraDeviceModelPageTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/CreateLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/LoRaWAN/EditLoraDeviceModel.razor
- src/AzureIoTHub.Portal/Client/assets/package-lock.json
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/DeviceModelCommand.cs
> Add a RegexMask on command frame to prevent non-hexadecimal characters

- src/AzureIoTHub.Portal/Client/wwwroot/css/app.css
> Fix blazor-error-ui text and links color in dark mode #963

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/CreateDevicePageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Devices/DeviceToDuplicateSelectorTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Services/DeviceLayoutServiceTests.cs
- src/AzureIoTHub.Portal/Client/Enums/DeviceSaveAction.cs
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceToDuplicateSelector.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/DeviceLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/IDeviceLayoutService.cs
- src/AzureIoTHub.Portal/Client/_Imports.razor
> Add save and duplicate device #616

- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal/Client/assets/package-lock.json
> Use npm ci to restore npm packages during build #793

- src/AzureIoTHub.Portal.Server.Tests.Unit/Pages/Settings/DeviceTagsPageTests.cs
- src/AzureIoTHub.Portal/Client/Models/DeviceTagModel.cs
- src/AzureIoTHub.Portal/Client/Pages/Settings/DeviceTagsPage.razor
> Disable the edition of existing tags names on Device Tags Settings page  #1002

- docs/open-api.md
- mkdocs.yml
- requirements.txt
What's new?
- Usage of the plugin [mkdocs-swagger-ui-tag](https://github.com/blueswen/mkdocs-swagger-ui-tag) to:
- Remove Try It Out on swagger ui
-  Handle dark mode when rendering swagger ui
- Enable filtering tagged operations
> Add the plugin mkdocs-swagger-ui-tag to remove "try it out" on swagger

- src/AzureIoTHub.Portal.Server.Tests.Unit/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/Managers/DeviceModelImageManagerTest.cs
- src/AzureIoTHub.Portal.Server.Tests.Unit/ProductionConfigHandlerTests.cs
- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Managers/DeviceModelImageManager.cs
- src/AzureIoTHub.Portal/Server/Managers/IDeviceModelImageManager.cs
- src/AzureIoTHub.Portal/Server/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Add Cache Control when uploading devices models images

- .github/workflows/build.yml
- src/AzureIoTHub.Portal/Client/AzureIoTHub.Portal.Client.csproj
- src/Dockerfile
> Fix #1060 - use npm ci during CI phase only

- src/.editorconfig
- src/AzureIoTHub.Portal.Tests.Unit/Server/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/ProductionConfigHandlerTests.cs
- src/AzureIoTHub.Portal/Server/ConfigHandler.cs
- src/AzureIoTHub.Portal/Server/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal/Server/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
What's new?
- Related to #1062 
- Fix #1045
> Merge Hotfix from 2.7.1

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/DevicesModels/DeviceModelDetailsPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Services/DeviceLayoutServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Mappers/LoRaDeviceModelMapperTests.cs
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/CreateDeviceModelPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceToDuplicateSelector.razor
- src/AzureIoTHub.Portal/Client/Services/DeviceLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/IDeviceLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/ILoRaWanDeviceClientService.cs
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceDetailsValidator.cs
- src/AzureIoTHub.Portal/Client/Validators/LoRaDeviceModelValidator.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Mappers/IDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/IDeviceTwinMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IDeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IDeviceModel.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceBase.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceDetails.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/LoRaWAN/LoRaDeviceModel.cs
> Fix #969 - Refactor LoRa Device model and LoRaDevice classes

- src/AzureIoTHub.Portal/Client/Pages/Devices/CreateDevicePage.razor
> Fix #1098 - In new device creation, search models that contain a text

- .github/workflows/arm-ttk.yml
- src/AzureIoTHub.Portal.sln
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
> Add PostgreSQL database to deployment

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/CreateEdgeModelsPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Mappers/EdgeDeviceMapperTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeDeviceServiceTest.cs
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/EdgeDevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeModelMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/IEdgeDeviceMapper.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeDevicesService.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IEdgeDevicesService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeModule.cs
> Task 988/Refactor EdgeDevicesController

- src/AzureIoTHub.Portal/Client/Pages/DeviceConfigurations/DeviceConfigurationListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/EdgeModelListPage.razor
- src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> Fixe: #1095 - In lists, when we are in splitscreen (for example), the list display is not easely readable.

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANDeviceServiceTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
- src/AzureIoTHub.Portal/Server/Services/ILoRaWANDeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/LoRaWANDeviceService.cs
> Fix #981 - Refactor LoRaWAN device controller

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DeviceModelPropertiesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelPropertiesServiceTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelPropertiesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DeviceModelPropertiesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceModelPropertiesService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceModelPropertiesService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #984 - Refactor DeviceModelPropertiesController

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DevicePropertyServiceTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Services/DevicePropertyService.cs
- src/AzureIoTHub.Portal/Server/Services/IDevicePropertyService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Refactor device controller #985

- README.md
- templates/azuredeploy.json
- templates/azuredeployUI.json
- templates/portalDeployWithLoRa.json
- templates/portalDeployWithoutLoRa.json
What's new?
- Fix #1180
- Fix #1181
> Fix PostgreSQL arm deployment on V3

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/CreateEdgeModelsPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/EdgeModelDetailPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Validators/IoTEdgeRouteValidatorTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Helpers/ConfigHelperTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Mappers/EdgeModelMapperTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ConfigServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/CreateEdgeModelsPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/EdgeModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Validators/IoTEdgeRouteValidator.cs
- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeModelMapper.cs
- src/AzureIoTHub.Portal/Server/Mappers/IEdgeDeviceModelMapper.cs
- src/AzureIoTHub.Portal/Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal/Server/Services/IConfigService.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeModel.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeRoute.cs
> Define EdgeHub routes in edge models

- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ConcentratorMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ConcentratorMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeDeviceMetricExporterServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeDeviceMetricLoaderServiceTests.cs
- src/AzureIoTHub.Portal/Server/Extensions/QuartzConfiguratorExtension.cs
- src/AzureIoTHub.Portal/Server/Services/ConcentratorMetricExporterService.cs
- src/AzureIoTHub.Portal/Server/Services/ConcentratorMetricLoaderService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceMetricExporterService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceMetricLoaderService.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeDeviceMetricExporterService.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeDeviceMetricLoaderService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Fix #1200 - Add Metrics services to Quartz Jobs

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911150200_Add DeviceModelCommand.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911150200_Add DeviceModelCommand.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceModelCommandSeeder.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHubPortal.Domain/Entities/DeviceModelCommand.cs
> Add migration of device model commands from st table to database #1209

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911135612_Add DeviceTag.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911135612_Add DeviceTag.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/DeviceTagSeeder.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHubPortal.Domain/Entities/DeviceTag.cs
> Add migration of device tags from st table to database #1207

- src/AzureIoTHubPortal.Domain/Exceptions/BaseException.cs
- src/AzureIoTHubPortal.Domain/Exceptions/InternalServerErrorException.cs
- src/AzureIoTHubPortal.Domain/Exceptions/ResourceAlreadyExistsException.cs
- src/AzureIoTHubPortal.Domain/Exceptions/ResourceNotFoundException.cs
What's new?
- Refactor: make nullable arguments as nullable in the declaration
> Refactor: make nullable arguments as nullable in the declaration

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911182352_Add EdgeDeviceModelCommand.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220911182352_Add EdgeDeviceModelCommand.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelCommandSeeder.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDeviceModelCommand.cs
> Add migration of edge model commands from st table to database #1218

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal/Client/assets/package-lock.json
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesController.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/DevicesControllerBase.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesController.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IDeviceService.cs
> Refactor DevicesControllerBase #986

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220915075056_Add Description Property on EdgeModel.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220915075056_Add Description Property on EdgeModel.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelSeeder.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDeviceModel.cs
> Add missing Description column on Edge Device Model #1246

- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelServiceTests.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceModelService.cs
> Fix missing compute device model image uri #1248

- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelPropertiesServiceTests.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceModelPropertiesService.cs
> Fix loading device model properties on a device #1249

- docs/dev-guide/testing/unit-tests-common-practices.md
- docs/dev-guide/testing/unit-tests-on-blazor-components.md
- mkdocs.yml
> Add docs about unit tests practices #1168

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220921080852_Add ModuleName Property on EdgeDeviceModelCommand.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20220921080852_Add ModuleName Property on EdgeDeviceModelCommand.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/EdgeDeviceModelCommandRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/EdgeDeviceModelRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/EdgeModelRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Seeds/EdgeDeviceModelCommandSeeder.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/EdgeDeviceModelCommandRepositoryTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/EdgeDeviceModelRepositoryTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/UnitTests/Bases/BackendUnitTest.cs
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/EdgeModelDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/EdgeModule/ModuleDialogTab3.razor
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceModelCommandProfile.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceModelProfile.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal/Server/Services/IEdgeModelService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeModuleCommand.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDeviceModelCommand.cs
- src/AzureIoTHubPortal.Domain/Repositories/IEdgeDeviceModelCommandRepository.cs
- src/AzureIoTHubPortal.Domain/Repositories/IEdgeDeviceModelRepository.cs
- src/AzureIoTHubPortal.Domain/Repositories/IEdgeModelRepository.cs
> Rework edge model service to use database

- src/AzureIoTHub.Portal/Server/Mappers/LoRaDeviceMapper.cs
> Add missing mapping on ClassType between lorawan and twin #1274

- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceTagServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWANCommandServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWanDeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/UnitTests/Bases/BackendUnitTest.cs
- src/AzureIoTHub.Portal/Server/Mappers/EnumerableProfile.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
> Enable AutoMapper dependency injection to load all profiles #1264

- src/AzureIoTHub.Portal.Infrastructure/Repositories/GenericRepository.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/GenericRepositoryTests.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/PaginatedResult.cs
- src/AzureIoTHubPortal.Domain/IRepository.cs
> Add generic pagination on generic repository #1304

- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWanDeviceServiceTests.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal/Server/Services/LoRaWanDeviceService.cs
> Fix device create/update/delete on azure iot hub #1308

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221004121605_Add EdgeDevice.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221004121605_Add EdgeDevice.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/EdgeDeviceRepository.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/EdgeDeviceRepositoryTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Jobs/SyncEdgeDeviceJobTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeDeviceServiceTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ExternalDeviceServiceTests.cs
- src/AzureIoTHub.Portal/Server/Jobs/SyncEdgeDeviceJob.cs
- src/AzureIoTHub.Portal/Server/Mappers/EdgeDeviceProfile.cs
- src/AzureIoTHub.Portal/Server/Services/EdgeDevicesService.cs
- src/AzureIoTHub.Portal/Server/Services/ExternalDeviceService.cs
- src/AzureIoTHub.Portal/Server/Services/IExternalDeviceService.cs
- src/AzureIoTHub.Portal/Server/Startup.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDevice.cs
- src/AzureIoTHubPortal.Domain/Repositories/IEdgeDeviceRepository.cs
> Feature/#1281_-_Syncronize edge device between IoT hub and portal database

- src/AzureIoTHub.Portal.Tests.Unit/Server/Helpers/ConfigHelperTest.cs
- src/AzureIoTHub.Portal/Client/Pages/EdgeModels/EdgeModule/ModuleDialog.razor
- src/AzureIoTHub.Portal/Server/Helpers/ConfigHelper.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/IoTEdgeModule.cs
Fix #1170
What's new?
- Update unit tests on ConfigHelper
- Add info link on how to configure a container create options
- Update unit test GenerateModulesContentShouldReturnValue
> Add container create options on create/edit edge module #1170

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/EdgeDevicesControllerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/LoRaWAN/LoRaWANDevicesControllerTests.cs
- src/AzureIoTHub.Portal/Server/Controllers/v1.0/LoRaWAN/LoRaWANConcentratorsController.cs
- src/AzureIoTHub.Portal/Server/Mappers/ConcentratorProfile.cs
- src/AzureIoTHub.Portal/Server/Services/LoRaWANConcentratorService.cs
- src/AzureIoTHub.Portal/Shared/Models/v1.0/PaginatedResult.cs
> Bugfix: Add missing next page on concentrators listing

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/CreateEdgeDevicePageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/EdgeDeviceDetailPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/EdgeDeviceToDuplicateSelectorTests.cs
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/CreateEdgeDevicePage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceDetailPage.razor
- src/AzureIoTHub.Portal/Client/Pages/EdgeDevices/EdgeDeviceToDuplicateSelector.razor
- src/AzureIoTHub.Portal/Client/Program.cs
- src/AzureIoTHub.Portal/Client/Services/EdgeDeviceLayoutService.cs
- src/AzureIoTHub.Portal/Client/Services/IEdgeDeviceLayoutService.cs
> Feature/#1132 Save and Duplicate Edge Device

- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221004121605_Add EdgeDevice.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/PortalDbContextModelSnapshot.cs
- src/AzureIoTHubPortal.Domain/Entities/EdgeDevice.cs
> BugFix/#1373_-_Issue when creating a new Edge Device 

- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/DeviceModelPropertiesControllerTests.cs
What's new?
- Remove unused references on local variables
> Remove Useless assignment to local variable in in DeviceModelPropertiesControllerTests

- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/LoRaWan/EditLoraDeviceTests.cs
What's new?
- Remove unused reference to local variable in EditLoraDeviceTest
> Remove Useless assignment to local variable in EditLoraDeviceTest

- docs/dev-guide.md
What's new?
- Remove documentation about Storage account usage
- Remove documentation about default tags that are used in the IoT Hub
> [Docs] Remove obsolete documentation since v3

- src/docker-compose.yml
What's new?
- Set default PostgreSQL image version to 14 to prevent Docker conflicts
> Set default PostgreSQL image version to 14

- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/CreateEdgeModelsPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModule/SystemModuleDialog.razor
- src/AzureIoTHub.Portal.Server/Helpers/ConfigHelper.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/EdgeModelSystemModule.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/SystemModuleDialogTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Helpers/ConfigHelperTest.cs
> Fix/1416 - Enable setting container create options on system modules in edge models

- src/AzureIoTHub.Portal.Server/Services/ConfigService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/ConfigServiceTests.cs
What's new?
- Use dedicated exception handling in ConfigService
> Fix Code QL on ConfigService

- src/AzureIoTHub.Portal.Server/Jobs/SyncConcentratorsJob.cs
- src/AzureIoTHub.Portal.Server/Jobs/SyncDevicesJob.cs
- src/AzureIoTHub.Portal.Server/Jobs/SyncEdgeDeviceJob.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Jobs/SyncConcentratorsJobTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Jobs/SyncDevicesJobTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Jobs/SyncEdgeDeviceJobTest.cs
> BugFix/#1421_-_Unable to delete device in database when the device did not exist in IoTHub

- src/AzureIoTHub.Portal.Client/Pages/DeviceModels/DeviceModelListPage.razor
> Filter devices by device model

- src/AzureIoTHub.Portal.Domain/Entities/Concentrator.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221115105521_Set ClientThumbprint as nullable.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221115105521_Set ClientThumbprint as nullable.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/LoRaWAN/ConcentratorDto.cs
> Bugfix : Set Concentrator ClientThumbprint as nullable

- templates/portalDeployWithLoRa.bicep
- templates/portalDeployWithoutLoRa.bicep
> Add dependsOn database on portal app service #1575

- src/AzureIoTHub.Portal.Client/Services/DeviceTagSettingsClientService.cs
> Fix #1609 - Do not dispose the String content when updating the tag

- src/AzureIoTHub.Portal.Application/AzureIoTHub.Portal.Application.csproj
- src/AzureIoTHub.Portal.Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal.sln
> Fix #1546 - Add application Class library to the solution

- src/AzureIoTHub.Portal.Server/Jobs/SyncDevicesJob.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Jobs/SyncDevicesJobTests.cs
> Fix #1635 - discard device sync if its modelid is not provided

- src/AzureIoTHub.Portal.Client/Components/Commons/Labels.razor
- src/AzureIoTHub.Portal.Client/Pages/DeviceModels/DeviceModelListPage.razor
- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/EdgeDeviceListPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModelListPage.razor
- src/AzureIoTHub.Portal.Domain/Entities/IDevice.cs
- src/AzureIoTHub.Portal.Domain/Entities/LorawanDevice.cs
- src/AzureIoTHub.Portal.Domain/IRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221205101458_Introduce DeviceBase Entity.Designer.cs
- src/AzureIoTHub.Portal.Infrastructure/Migrations/20221205101458_Introduce DeviceBase Entity.cs
- src/AzureIoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/GenericRepository.cs
- src/AzureIoTHub.Portal.Server/Mappers/EdgeDeviceProfile.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceModelService.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/DeviceListItem.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IoTEdgeListItem.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IoTEdgeModelListItem.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Components/Commons/LabelsTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceModelServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
- src/AzureIoTHub.Portal.sln
> Display labels at the device list page

- src/AzureIoTHub.Portal.Client/Pages/Devices/DeviceListPage.razor
- src/AzureIoTHub.Portal.Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/DeviceListItem.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/Devices/DevicesListPageTests.cs
> Feature: Update devices pagination to distinguish devices that have telemetry #1641

- .github/workflows/publish.yml
What's new?
- Add missing step docker/metadata-action on arm_templates job, required by the step `Update IoTHub Portal docker image tag in app_service.bicep`
> Add missing step docker/metadata-action on arm_templates job

- src/AzureIoTHub.Portal.Application/Services/IEdgeModelService.cs
- src/AzureIoTHub.Portal.Client/Components/EdgeModels/EdgeModelSearch.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModelListPage.razor
- src/AzureIoTHub.Portal.Client/Services/EdgeModelClientService.cs
- src/AzureIoTHub.Portal.Client/Services/IEdgeModelClientService.cs
- src/AzureIoTHub.Portal.Client/_Imports.razor
- src/AzureIoTHub.Portal.Server/Controllers/v1.0/EdgeModelsController.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Server/Services/EdgeDevicesService.cs
- src/AzureIoTHub.Portal.Server/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/DeviceListFilter.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/EdgeModelFilter.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/Filters/PaginationFilter.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Components/EdgeModels/EdgeModelSearchTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/CreateEdgeDevicePageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeDevices/EdgeDeviceListPageTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/EdgeModelsListPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Controllers/v1.0/EdgeModelsControllerTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
> Add search by name or description on edge models #1362

- src/AzureIoTHub.Portal.Client/App.razor
- src/AzureIoTHub.Portal.Client/AzureIoTHub.Portal.Client.csproj
- src/AzureIoTHub.Portal.Client/Program.cs
> Feature: remove blazored modal references

- src/AzureIoTHub.Portal.Infrastructure/Jobs/SyncEdgeDeviceJob.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Jobs/SyncEdgeDeviceJobTest.cs
> Fix #1804 - encapsulate sync job by a try-catch per device

- .github/workflows/build.yml
What's new?
- Remove Team Reviewers in github action that push the PR for a API documentation update.
> Remove Team reviewers to automated PR when API documentation updates

- src/AzureIoTHub.Portal.Server/Services/DeviceService.cs
- src/AzureIoTHub.Portal.Server/Services/DeviceServiceBase.cs
- src/AzureIoTHub.Portal.Server/Services/LoRaWanDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/DeviceServiceTests.cs
> Fix Bug: Failed to delete a device that is not present in IoT Hub #1836

- src/AzureIoTHub.Portal.Client/wwwroot/index.html
> Fix remove reference blazored modal of index html

- src/AzureIoTHub.Portal.Infrastructure/ConnectionAuthMethod.cs
- src/AzureIoTHub.Portal.Server/Services/LoRaWanDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/LoRaWanDeviceServiceTests.cs
What's new?
- Fix error in logs when trying to deserialize an event that is not coming from a LoRa device.
> Process LoRa Message only if comming from a device and can be deserialized

- src/AzureIoTHub.Portal.Client/Pages/Settings/DeviceTagsPage.razor
- src/AzureIoTHub.Portal.Tests.E2E/Pages/EdgeModelPage.cs
> Fix #1901 - Add class name in rows to identfy tag in DOM

- src/AzureIoTHub.Portal.Client/Components/Concentrators/ConcentratorSearch.razor
- src/AzureIoTHub.Portal.Client/Models/ConcentratorSearchInfo.cs
- src/AzureIoTHub.Portal.Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
- src/AzureIoTHub.Portal.Tests.Unit/Client/Components/Concentrators/ConcentratorSearchTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/LoRaWan/Concentrator/ConcentratorListPageTests.cs
> Fix #1902 - Fix query search parameters in lorawan concentrator list page

- src/docker-compose.yml
- src/e2e-docker-compose.yml
What's new?
- Fix e2e tests by enabling healthcheck on postgres services
> Bugfix: Add healthcheck on postgres services

- .github/workflows/ci-tests.yml
- src/AzureIoTHub.Portal.Domain/ConfigHandler.cs
- src/AzureIoTHub.Portal.Domain/Shared/Constants/CloudProviders.cs
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerBase.cs
- src/AzureIoTHub.Portal.Infrastructure/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionConfigHandler.cs
- src/AzureIoTHub.Portal.Server/AzureIoTHub.Portal.Server.csproj
- src/AzureIoTHub.Portal.Server/Startup.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/ProductionConfigHandlerTests.cs
- src/e2e-docker-compose.yml
- Add "CloudProvider" in configuration
- Add AmazonIoTClient and AmazonIotDataClient configurations when CloudProvider is AWS
What's new?
- Fix #1793
> #1793 Add AmazonIoTClient and AmazonIotDataClient configurations

- .github/workflows/aws-cfn-lint.yml
> 1942 task updates and maintenance

- src/AzureIoTHub.Portal.sln
- templates/aws/awsdeploy.yml
What's new?
- Fix cloud formation script
> Fix AWS cloud formation template

- src/AzureIoTHub.Portal.Client/Constants/Theme.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Constants/ThemeTests.cs
What's new?
- Palette is obsolete and will be abstract in a future update of Mudblazor. It must be replaced by PaletteLight or PaletteDark or custom implementation. In our case, we need to replace it by PaletteLight.
> Replace deprecated Palette by PaletteLight

- src/AzureIoTHub.Portal.Application/Mappers/AWS/AWSDeviceThingProfile.cs
- src/AzureIoTHub.Portal.Application/Services/AWS/IAWSExternalDeviceService.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSDeviceService.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSExternalDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Services/AWSDeviceServiceTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Services/AWSExternalDeviceServiceTest.cs
- Delete AWS Device
- TU Delete AWS Device
What's new?
- Fix #1922
> #1922 Delete AWS IoT Device

- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/CreateEdgeModelsPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModelDetailPage.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModule/ModuleDialog.razor
- src/AzureIoTHub.Portal.Domain/ConfigHandler.cs
- src/AzureIoTHub.Portal.Domain/Entities/EdgeDeviceModel.cs
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerBase.cs
- src/AzureIoTHub.Portal.Infrastructure/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAWSConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAzureConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AwsConfigService.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/AWSServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Postgres/Migrations/20230525074805_Add Aws DeploymentId.Designer.cs
- src/AzureIoTHub.Portal.Postgres/Migrations/20230525074805_Add Aws DeploymentId.cs
- src/AzureIoTHub.Portal.Postgres/Migrations/20230526083144_Change IdProvider to ExternalIdentifier.Designer.cs
- src/AzureIoTHub.Portal.Postgres/Migrations/20230526083144_Change IdProvider to ExternalIdentifier.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IoTEdgeModelListItem.cs
- src/AzureIoTHub.Portal.Shared/Models/v1.0/IoTEdgeModule.cs
- src/AzureIoTHub.Portal.Tests.Unit/Client/Pages/EdgeModels/EdgeModelDetailPageTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Services/AWS_Tests/AwsConfigTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
What's new?
- (Updated) #2069
- #2071 
- #2072
> Update and delete green grass deployment

- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSExternalDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Services/AWSExternalDeviceServiceTest.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Services/AwsExternalDeviceServiceTests.cs
Steps to delete the thing:
- List All the thing principals
- Detach all thing principals
- Delete the thing
What's new?
- #2147
> detach associated certificate in thing

- src/AzureIoTHub.Portal.Domain/ConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ConfigHandlerBase.cs
- src/AzureIoTHub.Portal.Infrastructure/DevelopmentConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAWSConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/ProductionAzureConfigHandler.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AwsExternalDeviceService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/DevelopmentConfigHandlerTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/ProductionAWSConfigHandlerTests.cs
- templates/aws/awsdeploy.yml
What's new?
- Update application settings to prepare the deployment
> Update deployement parameters

- src/AzureIoTHub.Portal.Application/Mappers/AWS/AWSDeviceThingProfile.cs
- src/AzureIoTHub.Portal.Domain/Repositories/IDeviceModelRepository.cs
- src/AzureIoTHub.Portal.Domain/Repositories/IEdgeDeviceModelRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Jobs/AWS/SyncGreenGrassDevicesJob.cs
- src/AzureIoTHub.Portal.Infrastructure/Jobs/AWS/SyncThingsJob.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/DeviceModelRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Repositories/EdgeDeviceModelRepository.cs
- src/AzureIoTHub.Portal.Infrastructure/Services/AWS/AWSEdgeDevicesService.cs
- src/AzureIoTHub.Portal.Infrastructure/Startup/AWSServiceCollectionExtension.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Jobs/AWS/SyncGreenGrassDevicesJobTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Jobs/AWS/SyncThingsJobTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/DeviceModelRepositoryTests.cs
- src/AzureIoTHub.Portal.Tests.Unit/Infrastructure/Repositories/EdgeDeviceModelRepositoryTests.cs
- Sync AWS IoT Edge Device
- TU sync IoT Edge Device
- GetByName async for DeviceModel and EdgeDeviceModel
What's new?
- Fix #2075
> #2075 Sync AWS IoT Edge Device

- src/AzureIoTHub.Portal.Client/Pages/EdgeDevices/ConnectionStringDialog.razor
- src/AzureIoTHub.Portal.Client/Pages/EdgeModels/EdgeModelDetailPage.razor
- src/AzureIoTHub.Portal.Infrastructure/Services/EdgeModelService.cs
- src/AzureIoTHub.Portal.Tests.Unit/Server/Services/EdgeModelServiceTest.cs
> #2161 fix edge model update

- src/IoTHub.Portal.Client/Handlers/ProblemDetailsHandler.cs
- src/IoTHub.Portal.Client/Program.cs
- src/IoTHub.Portal.Client/Shared/Error.razor
- src/IoTHub.Portal.Tests.Unit/Client/Handlers/ProblemDetailsHandlerTests.cs
- src/IoTHub.Portal.Tests.Unit/Client/Pages/Shared/ErrorTests.cs
> Feature: Add redirect button on snackbar when http status code is 401

- .github/workflows/arm-ttk.yml
- .github/workflows/publish.yml
- .gitignore
- .gitmodules
- templates/azure/portal_with_lorawan_and_starter_kit.bicep
> Feature: Add iotedge-lorawan-starterkit as git submodule

- src/IoTHub.Portal.Client/IoTHub.Portal.Client.csproj
What's new?
- Uninstall Microsoft.AspNetCore.Components.Web.Extensions dependency: The package Microsoft.AspNetCore.Components.Web.Extensions is not used and it is deprecated.
> Feature: Remove unused and depcrecated package Microsoft.AspNetCore.Components.Web.Extensions

- src/IoTHub.Portal.Tests.Unit/Client/Services/DeviceModelsClientServiceTests.cs
- src/IoTHub.Portal.Tests.Unit/Client/Services/EdgeModelClientServiceTest.cs
- src/IoTHub.Portal.Tests.Unit/Client/Services/LoRaWanDeviceModelsClientServiceTests.cs
> Bugfix: Fix unit tests on IoTHub.Portal.Tests.Unit.Client.Services

- .github/dependabot.yml
What's new?
- FIx #2682 
- Remove dependabot npm ecosystem: No more used by IotHUb Portal client
> Feature: Dependabot ignores major versions on nuget packages

- docs/b2c-applications.md
#2601 
What's new?
- Added detailed instructions for setting up OpenID Connect in the Azure AD B2C tenant documentation. This includes steps to determine the OpenID Authority and find the OpenID Metadata URL, ensuring comprehensive guidance for users during Azure deployment setup.
> Update documentation of OpenID Connect Setup Instructions for Azure

- src/IoTHub.Portal.Infrastructure/Startup/AzureServiceCollectionExtension.cs
> Fix #2942 - Add LoraWan service dependency before adding the http client

- src/IoTHub.Portal.Infrastructure/Services/LoRaWanManagementService.cs
- src/IoTHub.Portal.Tests.Unit/Infrastructure/Services/LoRaWanManagementServiceTests.cs
Solve Command sending issue. httpClient was not correctly loaded at LNS Management Service initialization. 
- Fix #913
> Fix - Failed to execute LoRaWAN Command

- src/Dockerfile
What's new?
- Replace node build image by dotnet/sdk image to build IoT Hub Portal
- Remove unused build params:  -p:ClientAssetsRestoreCommand="npm ci"
> Bugfix: Replace node build image by dotnet/sdk image

- src/IoTHub.Portal.Infrastructure/PortalDbContext.cs
- src/IoTHub.Portal.MySql/Migrations/20240503170430_Fix #2980 - delete tag values in cascade when deleting devices.Designer.cs
- src/IoTHub.Portal.MySql/Migrations/20240503170430_Fix #2980 - delete tag values in cascade when deleting devices.cs
- src/IoTHub.Portal.Postgres/Migrations/20240503170119_Fix #2980 - delete tag values in cascade when deleting devices.Designer.cs
- src/IoTHub.Portal.Postgres/Migrations/20240503170119_Fix #2980 - delete tag values in cascade when deleting devices.cs
- src/IoTHub.Portal.Postgres/Migrations/PortalDbContextModelSnapshot.cs
> Fix #2980 - Add cascade delete to foreign keys
